AWSTemplateFormatVersion: "2010-09-09"
Description: Provision VPC-EC2

Parameters:
  ResouceTagName:
    Description: ResouceTagName by this name
    Type: String
    Default: XX

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: cdk-app

Resources:
  XXVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      Tags:
        - Key: Name
          Value: !Sub ${ResouceTagName}-VPC

  XXInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ResouceTagName}-InternetGateway

  # InternetGateway をVPCにアタッチ
  XXAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref XXVPC
      InternetGatewayId: !Ref XXInternetGateway

  XXPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-3a
      VpcId: !Ref XXVPC
      CidrBlock: 10.1.0.0/24
      Tags:
        - Key: Name
          Value: !Sub ${ResouceTagName}-PublicSubnet

  XXPublicSubnetRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref XXVPC
      Tags:
        - Key: Name
          Value: !Sub ${ResouceTagName}-PublicSubnetRouteTable

  # PublicSubnet-インターネット間のルーティング
  XXPublicSubnetToInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref XXPublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref XXInternetGateway

  # ルートテーブルをサブネットに関連付け
  XXAssoPublicSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref XXPublicSubnet
      RouteTableId: !Ref XXPublicSubnetRouteTable

  XXEC2:
    Type: AWS::EC2::Instance
    Properties:
      # Amazon Linux 2
      ImageId: ami-0dcd015c93067a97b
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref XXPublicSubnet
          GroupSet:
            - !Ref XXEC2SecurityGroup
      # EC2作成時にインスタンスプロファイルを指定
      IamInstanceProfile:
        Ref: XXSessionManagerIamInstanceProfile
      Tags:
          - Key: Name
            Value: !Sub ${ResouceTagName}-EC2

  XXSsmSessionManagerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      RoleName: 'XXSsmSessionManagerIamRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  XXSessionManagerIamInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - !Ref XXSsmSessionManagerIamRole

  XXEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg-cf
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: !Ref XXVPC
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0